# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design_updated.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frm_main(object):
    def setupUi(self, frm_main):
        frm_main.setObjectName(_fromUtf8("frm_main"))
        frm_main.resize(896, 767)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frm_main.sizePolicy().hasHeightForWidth())
        frm_main.setSizePolicy(sizePolicy)
        frm_main.setMinimumSize(QtCore.QSize(896, 767))
        frm_main.setMaximumSize(QtCore.QSize(896, 767))
        self.slider_lower = QtGui.QSlider(frm_main)
        self.slider_lower.setGeometry(QtCore.QRect(320, 358, 251, 19))
        self.slider_lower.setMinimum(10)
        self.slider_lower.setMaximum(40)
        self.slider_lower.setOrientation(QtCore.Qt.Horizontal)
        self.slider_lower.setObjectName(_fromUtf8("slider_lower"))
        self.slider_upper = QtGui.QSlider(frm_main)
        self.slider_upper.setGeometry(QtCore.QRect(320, 402, 251, 19))
        self.slider_upper.setMinimum(10)
        self.slider_upper.setMaximum(40)
        self.slider_upper.setProperty("value", 40)
        self.slider_upper.setOrientation(QtCore.Qt.Horizontal)
        self.slider_upper.setInvertedAppearance(False)
        self.slider_upper.setObjectName(_fromUtf8("slider_upper"))
        self.line = QtGui.QFrame(frm_main)
        self.line.setGeometry(QtCore.QRect(320, 456, 256, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.lbl_lower_current_title = QtGui.QLabel(frm_main)
        self.lbl_lower_current_title.setGeometry(QtCore.QRect(320, 470, 91, 16))
        self.lbl_lower_current_title.setObjectName(_fromUtf8("lbl_lower_current_title"))
        self.lbl_set_lower = QtGui.QLabel(frm_main)
        self.lbl_set_lower.setGeometry(QtCore.QRect(522, 470, 54, 16))
        self.lbl_set_lower.setFrameShape(QtGui.QFrame.Box)
        self.lbl_set_lower.setObjectName(_fromUtf8("lbl_set_lower"))
        self.lbl_upper_current_title = QtGui.QLabel(frm_main)
        self.lbl_upper_current_title.setGeometry(QtCore.QRect(320, 492, 93, 16))
        self.lbl_upper_current_title.setObjectName(_fromUtf8("lbl_upper_current_title"))
        self.lbl_set_upper = QtGui.QLabel(frm_main)
        self.lbl_set_upper.setGeometry(QtCore.QRect(522, 492, 54, 16))
        self.lbl_set_upper.setFrameShape(QtGui.QFrame.Box)
        self.lbl_set_upper.setObjectName(_fromUtf8("lbl_set_upper"))
        self.lbl_act_lower = QtGui.QLabel(frm_main)
        self.lbl_act_lower.setGeometry(QtCore.QRect(522, 339, 46, 16))
        self.lbl_act_lower.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_act_lower.setObjectName(_fromUtf8("lbl_act_lower"))
        self.lbl_act_upper = QtGui.QLabel(frm_main)
        self.lbl_act_upper.setGeometry(QtCore.QRect(522, 383, 46, 16))
        self.lbl_act_upper.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_act_upper.setObjectName(_fromUtf8("lbl_act_upper"))
        self.btn_Start = QtGui.QPushButton(frm_main)
        self.btn_Start.setGeometry(QtCore.QRect(360, 9, 151, 23))
        self.btn_Start.setObjectName(_fromUtf8("btn_Start"))
        self.btn_Stop = QtGui.QPushButton(frm_main)
        self.btn_Stop.setGeometry(QtCore.QRect(360, 38, 151, 23))
        self.btn_Stop.setObjectName(_fromUtf8("btn_Stop"))
        self.lbl_Temp_Title = QtGui.QLabel(frm_main)
        self.lbl_Temp_Title.setGeometry(QtCore.QRect(9, 67, 93, 16))
        self.lbl_Temp_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Temp_Title.setObjectName(_fromUtf8("lbl_Temp_Title"))
        self.lbl_Humidity_Title = QtGui.QLabel(frm_main)
        self.lbl_Humidity_Title.setGeometry(QtCore.QRect(443, 67, 73, 16))
        self.lbl_Humidity_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Humidity_Title.setObjectName(_fromUtf8("lbl_Humidity_Title"))
        self.lbl_Temp_Value = QtGui.QLabel(frm_main)
        self.lbl_Temp_Value.setGeometry(QtCore.QRect(9, 86, 421, 16))
        self.lbl_Temp_Value.setFrameShape(QtGui.QFrame.Box)
        self.lbl_Temp_Value.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Temp_Value.setObjectName(_fromUtf8("lbl_Temp_Value"))
        self.lbl_Humidity_Value = QtGui.QLabel(frm_main)
        self.lbl_Humidity_Value.setGeometry(QtCore.QRect(443, 86, 441, 16))
        self.lbl_Humidity_Value.setFrameShape(QtGui.QFrame.Box)
        self.lbl_Humidity_Value.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Humidity_Value.setObjectName(_fromUtf8("lbl_Humidity_Value"))
        self.gr_Temperature = PlotWidget(frm_main)
        self.gr_Temperature.setGeometry(QtCore.QRect(9, 107, 421, 192))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gr_Temperature.sizePolicy().hasHeightForWidth())
        self.gr_Temperature.setSizePolicy(sizePolicy)
        self.gr_Temperature.setObjectName(_fromUtf8("gr_Temperature"))
        self.gr_Humidity = PlotWidget(frm_main)
        self.gr_Humidity.setGeometry(QtCore.QRect(443, 107, 441, 192))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gr_Humidity.sizePolicy().hasHeightForWidth())
        self.gr_Humidity.setSizePolicy(sizePolicy)
        self.gr_Humidity.setObjectName(_fromUtf8("gr_Humidity"))
        self.lbl_Lower_Temp_Title = QtGui.QLabel(frm_main)
        self.lbl_Lower_Temp_Title.setGeometry(QtCore.QRect(320, 339, 113, 16))
        self.lbl_Lower_Temp_Title.setObjectName(_fromUtf8("lbl_Lower_Temp_Title"))
        self.lbl_Upper_Temp_Title = QtGui.QLabel(frm_main)
        self.lbl_Upper_Temp_Title.setGeometry(QtCore.QRect(320, 383, 113, 16))
        self.lbl_Upper_Temp_Title.setObjectName(_fromUtf8("lbl_Upper_Temp_Title"))
        self.btn_Apply_Limit = QtGui.QPushButton(frm_main)
        self.btn_Apply_Limit.setEnabled(True)
        self.btn_Apply_Limit.setGeometry(QtCore.QRect(320, 427, 251, 23))
        self.btn_Apply_Limit.setObjectName(_fromUtf8("btn_Apply_Limit"))
        self.lbl_Heat_Title = QtGui.QLabel(frm_main)
        self.lbl_Heat_Title.setGeometry(QtCore.QRect(9, 513, 65, 16))
        self.lbl_Heat_Title.setObjectName(_fromUtf8("lbl_Heat_Title"))
        self.lbl_Cooling = QtGui.QLabel(frm_main)
        self.lbl_Cooling.setGeometry(QtCore.QRect(310, 513, 63, 16))
        self.lbl_Cooling.setObjectName(_fromUtf8("lbl_Cooling"))
        self.lbl_Ao1 = QtGui.QLabel(frm_main)
        self.lbl_Ao1.setGeometry(QtCore.QRect(580, 510, 82, 16))
        self.lbl_Ao1.setObjectName(_fromUtf8("lbl_Ao1"))
        self.gr_Heat_State = PlotWidget(frm_main)
        self.gr_Heat_State.setGeometry(QtCore.QRect(9, 532, 291, 192))
        self.gr_Heat_State.setObjectName(_fromUtf8("gr_Heat_State"))
        self.gr_Cooling_state = PlotWidget(frm_main)
        self.gr_Cooling_state.setGeometry(QtCore.QRect(310, 532, 256, 192))
        self.gr_Cooling_state.setObjectName(_fromUtf8("gr_Cooling_state"))
        self.gr_Venting = PlotWidget(frm_main)
        self.gr_Venting.setGeometry(QtCore.QRect(577, 532, 301, 192))
        self.gr_Venting.setObjectName(_fromUtf8("gr_Venting"))

        self.retranslateUi(frm_main)
        QtCore.QMetaObject.connectSlotsByName(frm_main)

    def retranslateUi(self, frm_main):
        frm_main.setWindowTitle(_translate("frm_main", "Sensor processor", None))
        self.lbl_lower_current_title.setText(_translate("frm_main", "Current lower limit:", None))
        self.lbl_set_lower.setText(_translate("frm_main", "TextLabel", None))
        self.lbl_upper_current_title.setText(_translate("frm_main", "Current upper limit:", None))
        self.lbl_set_upper.setText(_translate("frm_main", "TextLabel", None))
        self.lbl_act_lower.setText(_translate("frm_main", "TextLabel", None))
        self.lbl_act_upper.setText(_translate("frm_main", "TextLabel", None))
        self.btn_Start.setText(_translate("frm_main", "Start measurement", None))
        self.btn_Stop.setText(_translate("frm_main", "Stop measurement", None))
        self.lbl_Temp_Title.setText(_translate("frm_main", "Actual temperature", None))
        self.lbl_Humidity_Title.setText(_translate("frm_main", "Actual humidity", None))
        self.lbl_Temp_Value.setText(_translate("frm_main", "TextLabel", None))
        self.lbl_Humidity_Value.setText(_translate("frm_main", "TextLabel", None))
        self.lbl_Lower_Temp_Title.setText(_translate("frm_main", "Lower temperature limit", None))
        self.lbl_Upper_Temp_Title.setText(_translate("frm_main", "Upper temperature limit", None))
        self.btn_Apply_Limit.setText(_translate("frm_main", "Apply limits", None))
        self.lbl_Heat_Title.setText(_translate("frm_main", "Heating state", None))
        self.lbl_Cooling.setText(_translate("frm_main", "Cooling state", None))
        self.lbl_Ao1.setText(_translate("frm_main", "AO1 - air venting", None))

from pyqtgraph import PlotWidget
